begin: 01-10-2021
end: 21-02-2023
data: data.csv
url: https://www.gov.br/planalto/pt-br/acompanhe-o-planalto/agenda-do-presidente-da-republica/

sp: https://www.saopaulo.sp.gov.br/agenda-governador/
rj: http://www.rj.gov.br/Agenda.aspx

